using UnityEngine.Networking;
using UnityEngine;

public class Player : NetworkBehaviour
{
	public enum player
	{
		one = 0,
		two = 1,
		three = 2,
		four = 3,
	}

	public float speed;
	public Rigidbody2D rb2d;
	public Animator ani;
	public GameObject wodsword;
	public GameObject magsword;
	public GameObject whisword;
	public GameObject flame;
	public GameObject magic;
	public GameObject arrow;
	public GameObject silverarrows;
	public GameObject bomba;
	public GameObject wan;
	public GameObject rang;
	public GameObject mrang;
	public GameObject food;
	public GameObject swordb;
	public GameObject lefttornado;
	public GameObject rightornado;
	public GameObject raft;
	public GameObject stepup;
	public GameObject stepside;
	public int rup;
	public int key;
	public int bomb;
	public int heart;
	public int maxhearts;
	public GameObject marker;
	public int cameragridx;
	public int cameragridy;
	public bool pausmark;
	public bool canmove;
	public bool cansword;
	public bool canitem;
	public bool woodsword;
	public bool canlamp;
	public bool lampready;
	public bool rlamp;
	public bool bigsheild;
	public bool canbomb;
	public int maxbomb;
	public bool hasfood;
	public bool hasarrows;
	public bool silverarrow;
	public bool bow;
	public bool bluering;
	public bool redring;
	public int defence;
	public bool letter;
	public string currentitem;
	public int itempos;
	public bool boomerang;
	public bool mboomerang;
	public bool canflute;
	public bool haswater;
	public bool fullwater;
	public bool rod;
	public bool powerbracelet;
	public bool stepladder;
	public bool mkey;
	public bool mbook;
	public bool hasraft;
	public bool bombup;
	public bool bombup2;
	public int dmg;
	public bool msword;
	public bool wsword;
	public GameObject dposition;
	public bool pausedmark;
	public GameObject dmposition;
	public bool pausedmmark;
	public Vector2 facing;
	public bool invincible;
	public int kb;
	public int posx;
	public int posy;
	public int dposx;
	public int dposy;
	public int dmposx;
	public int dmposy;
	public GameObject playertonet;
	public Vector3 camerapos;
	public GameObject managero;
	public GameObject hud;
	public GameObject bullet;
	public GameObject dung;
	public player pl;
}
